<a href="https://colab.research.google.com/github/mishad01/Data-Science-Machine-Learning/blob/main/Pattern%20Recognition/Lab2_Lab_Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
import numpy as np
import pandas as pd


In [96]:
df = pd.read_csv("/content/drive/MyDrive/Patter Recognition Lab Dataset /Employee.csv")

In [97]:
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [98]:
df.isna().sum()

Education                    0
JoiningYear                  0
City                         0
PaymentTier                  0
Age                          0
Gender                       0
EverBenched                  0
ExperienceInCurrentDomain    0
LeaveOrNot                   0
dtype: int64

In [99]:
df.shape

(4653, 9)

In [100]:
df.dtypes

Education                    object
JoiningYear                   int64
City                         object
PaymentTier                   int64
Age                           int64
Gender                       object
EverBenched                  object
ExperienceInCurrentDomain     int64
LeaveOrNot                    int64
dtype: object

In [101]:
df["Education"].unique()

array(['Bachelors', 'Masters', 'PHD'], dtype=object)

In [102]:
df["Education"].value_counts()

Education
Bachelors    3601
Masters       873
PHD           179
Name: count, dtype: int64

In [103]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

In [104]:
df.head()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0  Bachelors         2017  Bangalore            3   34    Male          No   
1  Bachelors         2013       Pune            1   28  Female          No   
2  Bachelors         2014  New Delhi            3   38  Female          No   
3    Masters         2016  Bangalore            3   27    Male          No   
4    Masters         2017       Pune            3   24    Male         Yes   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [105]:
print(label_encoder)

LabelEncoder()


In [106]:
df["Education"]=label_encoder.fit_transform(df["Education"])
df["City"]=label_encoder.fit_transform(df["City"])
df["Gender"]=label_encoder.fit_transform(df["Gender"])
df["EverBenched"]=label_encoder.fit_transform(df["EverBenched"])

In [107]:
df.head()

Education  JoiningYear  City  PaymentTier  Age  Gender  EverBenched  \
0          0         2017     0            3   34       1            0   
1          0         2013     2            1   28       0            0   
2          0         2014     1            3   38       0            0   
3          1         2016     0            3   27       1            0   
4          1         2017     2            3   24       1            1   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [108]:
df["Education"].unique()

array([0, 1, 2])

In [109]:
df.head()

Education  JoiningYear  City  PaymentTier  Age  Gender  EverBenched  \
0          0         2017     0            3   34       1            0   
1          0         2013     2            1   28       0            0   
2          0         2014     1            3   38       0            0   
3          1         2016     0            3   27       1            0   
4          1         2017     2            3   24       1            1   

   ExperienceInCurrentDomain  LeaveOrNot  
0                          0           0  
1                          3           1  
2                          2           0  
3                          5           1  
4                          2           1

In [110]:
y = df['LeaveOrNot'].values
X = df.iloc[:,0:8].values

In [111]:
X.shape

(4653, 8)

In [124]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

#Feature Scaling

In [125]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [126]:
X_train

array([[-0.50723758,  1.5665578 ,  0.24696159, ..., -1.22392262,
         2.94833993,  0.06046742],
       [-0.50723758, -1.64449028, -0.94062373, ..., -1.22392262,
        -0.33917392,  1.33921584],
       [-0.50723758, -1.64449028,  1.43454691, ..., -1.22392262,
        -0.33917392,  1.33921584],
       ...,
       [-0.50723758,  1.03138312,  0.24696159, ..., -1.22392262,
        -0.33917392,  0.69984163],
       [-0.50723758,  1.5665578 ,  1.43454691, ...,  0.81704512,
        -0.33917392,  1.33921584],
       [-0.50723758, -1.64449028, -0.94062373, ..., -1.22392262,
         2.94833993, -1.85765522]])

In [127]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [116]:
y_pred = classifier.predict(X_test)

In [117]:
y_pred, y_test

(array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 

#Generating performance metrics





In [118]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[491 128]
 [172 140]]


0.677765843179377

In [119]:
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

Precision: 0.5223880597014925


In [120]:
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.44871794871794873


In [121]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.4827586206896552
